version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
      - npm run cy:parallel
  post_build:
    commands:
      - aws s3 sync allure-report s3://reporte-de-pruebas-rc/
      - aws s3 cp --recursive --acl public-read s3://reporte-de-pruebas-rc/ s3://reporte-de-pruebas-rc/ --metadata-directive REPLACE
      - echo "The HTML report can be found here => https://reporte-de-pruebas-rc.s3.sa-east-1.amazonaws.com/index.html <="